# IMPORTANT: Replace mas.<env>.maap-project.org to match the target environment
spec:
  k8s:
    ingressStrategy: 'single-host'
  server:
    cheImage: 'mas.<env>.maap-project.org:5000/root/che7/che-server'
    cheImageTag: '7.25.2-maap'
    cheImagePullPolicy: Always
    devfileRegistryImage: 'mas.<env>.maap-project.org:5000/root/che-devfile-registry:7.25.2-maap'
    devfileRegistryPullPolicy: Always
    serverCpuLimit: 2
    serverMemoryLimit: 4Gi
    serverMemoryRequest: 1024Mi
    customCheProperties:
      CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": public, "nginx.ingress.kubernetes.io/rewrite-target": "/$1","nginx.ingress.kubernetes.io/ssl-redirect": true,"nginx.ingress.kubernetes.io/proxy-connect-timeout": "3600","nginx.ingress.kubernetes.io/proxy-read-timeout": "3600","nginx.ingress.kubernetes.io/proxy-body-size":"256m"}'
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
      CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: <username>-che
      CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: '0'
      CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: '0'
      CHE_INFRA_KUBERNETES_SERVER__STRATEGY: 'single-host'
      CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE: 'single-host'
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '604800000' # in milliseconds, 7 days hour before auto stopping workspace
      CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME: 'nfs-client-che'
  database:
    # when set to true, the operator skips deploying Postgres, and passes connection details of existing DB to Che server
    # otherwise a Postgres deployment is created
    externalDb: false
    # Postgres deployment in format image:tag. 
    postgresImage: 'mas.<env>.maap-project.org:5000/root/che7/che-postgres:7.25.2-maap'
  auth:
    # instructs operator on whether or not to deploy Keycloak/RH SSO instance. When set to true provision connection details
    externalIdentityProvider: false
    # image:tag used in Keycloak deployment
    identityProviderImage: 'mas.<env>.maap-project.org:5000/root/che7/che-keycloak:7.25.2-maap'

